version: 0.0
os: linux
files:
 - source: /django_project/
   destination: /home/ec2-user/django_project
 - source: /nginx/
   destination: /home/ec2-user/nginx
 - source: /scripts/
   destination: /home/ec2-user/scripts 
 - source: /
   destination: /home/ec2-user/docker-compose.yml 
 - source: /
   destination: /home/ec2-user/Dockerfile 
 - source: /
   destination: /home/ec2-user/entrypoint.sh 

permissions:
  - object: /home/ec2-user/django_project/manage.py
    owner: root
    # mode: 644(read and write permissions ), 4755(gives full control permissions)
    mode: 4755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
