version: 0.0
os: linux

files:
 - source: /
   destination: /home/ec2-user

permissions:
  - object: /home/ec2-user/django_project/manage.py
    owner: root
    mode: 4755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
